apiVersion: v1
kind: Service
metadata:
  name: envoy-mtls-proxy
  namespace: default
  labels:
    app: envoy-mtls-proxy
spec:
  selector:
    app: envoy-mtls-proxy
  ports:
    - name: proxy
      port: 3128
      targetPort: 3128
      protocol: TCP
  type: ClusterIP
