apiVersion: v1
kind: Service
metadata:
  name: demo-webserver
  namespace: default
  labels:
    app: demo-webserver
spec:
  selector:
    app: demo-webserver
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  type: ClusterIP
